name: shadowfox-fielding-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.5.3
  - numpy=1.21.6
  - matplotlib=3.5.3
  - seaborn=0.12.2
  - scipy=1.7.3
  - scikit-learn=1.2.2
  - jupyter=1.0.0
  - openpyxl=3.0.10
  - plotly=5.13.1
  - jupyterlab=3.6.3
  - pip=21.3.1
  - pip:
    - -r requirements.txt